config/routes.rb
Scholarize::Application.routes.draw do

  devise_for :students

  resources :scholarships
  root :to => 'scholarize#index'

end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
  attr_accessible :amount, :description, :quantity, :title
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scholarize_controller.rb
class ScholarizeController < ApplicationController
  # GET /scholarize
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  # GET /scholarships
  # GET /scholarships.json

  # Authenticate Students
  before_filter :authenticate_student!

  def index
    @scholarships = Scholarship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scholarships }
    end
  end

  # GET /scholarships/1
  # GET /scholarships/1.json
  def show
    @scholarship = Scholarship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scholarship }
    end
  end

  # GET /scholarships/new
  # GET /scholarships/new.json
  def new
    @scholarship = Scholarship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scholarship }
    end
  end

  # GET /scholarships/1/edit
  def edit
    @scholarship = Scholarship.find(params[:id])
  end

  # POST /scholarships
  # POST /scholarships.json
  def create
    @scholarship = Scholarship.new(params[:scholarship])

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully created.' }
        format.json { render json: @scholarship, status: :created, location: @scholarship }
      else
        format.html { render action: "new" }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scholarships/1
  # PUT /scholarships/1.json
  def update
    @scholarship = Scholarship.find(params[:id])

    respond_to do |format|
      if @scholarship.update_attributes(params[:scholarship])
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarships/1
  # DELETE /scholarships/1.json
  def destroy
    @scholarship = Scholarship.find(params[:id])
    @scholarship.destroy

    respond_to do |format|
      format.html { redirect_to scholarships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scholarize</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag :defaults %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/messages' %>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href='/'>Scholarize</a>

      <div class="nav-collapse">
        <ul class="nav">
          <li><a href="https://github.com/ermauliks/scholarize/blob/master/README.md">About</a></li>
        </ul>
      </div>
      <div id="student_nav" class="navbar-text pull-right">
        <% if student_signed_in? %>
            Signed in as <%= current_student.email %>. Not You ?
            <%= link_to 'Sign out', destroy_student_session_path %>
        <% else %>
            <%= link_to 'Register', new_student_registration_path %>
            or <%= link_to 'Sign in', new_student_session_path %>
        <% end %>
      </div>
    </div>
  </div>
  <!--navbar-inner-->
</div>
<!--navbar navbar-fixed-top-->
<div class="container">
  <div class="container-fluid">
    <div class="row-fluid">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/scholarize/index.html.erb
<div class="hero-unit">
  *Blank page*
    Want to help ?
  <br>
  <a href="https://trello.com/board/scholarize-org/51407f8de330aa233c001c90">Click Me !!</a>

    </div>

app/views/scholarships/_form.html.erb
<%= form_for(@scholarship) do |f| %>
  <% if @scholarship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scholarship.errors.count, "error") %> prohibited this scholarship from being saved:</h2>

      <ul>
      <% @scholarship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scholarships/edit.html.erb
<h1>Editing scholarship</h1>

<%= render 'form' %>

<%= link_to 'Show', @scholarship %> |
<%= link_to 'Back', scholarships_path %>

app/views/scholarships/index.html.erb
<h1>Listing scholarships</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Amount</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scholarships.each do |scholarship| %>
  <tr>
    <td><%= scholarship.title %></td>
    <td><%= scholarship.description %></td>
    <td><%= scholarship.amount %></td>
    <td><%= scholarship.quantity %></td>
    <td><%= link_to 'Show', scholarship %></td>
    <td><%= link_to 'Edit', edit_scholarship_path(scholarship) %></td>
    <td><%= link_to 'Destroy', scholarship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scholarship', new_scholarship_path %>

app/views/scholarships/new.html.erb
<h1>New scholarship</h1>

<%= render 'form' %>

<%= link_to 'Back', scholarships_path %>

app/views/scholarships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @scholarship.title %>
</p>

<p>
  <b>Description:</b>
  <%= @scholarship.description %>
</p>

<p>
  <b>Amount:</b>
  <%= @scholarship.amount %>
</p>

<p>
  <b>Quantity:</b>
  <%= @scholarship.quantity %>
</p>


<%= link_to 'Edit', edit_scholarship_path(@scholarship) %> |
<%= link_to 'Back', scholarships_path %>